---
title: "Analysis RQ1 Regression Decay of Efficiency"
date: "`r Sys.Date()`"
output: 
  rmdformats::downcute:
    code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
    downcute_theme: "chaos"
editor_options: 
  chunk_output_type: console
---

```{r packages, warning=F, message=F}
library(tidyverse)
library(brms)
```


# Import and wrangle data
```{r message=FALSE, warning=FALSE}
# import from data folder
load("data/teachers_study1_N40.RData")

# wrangle information on the plot type, ES, ...
plot_info <- study1 %>%
    pivot_longer(2:195, names_to = "variables", values_to = "values", 
                 values_transform = as.character) %>%
    dplyr::filter(str_detect(variables, "plot")) %>% # we only need the rows with info on plots
    tidyr::separate(col = values, into = c("type", "axis", "effsize"), # separate the info into three columns
                    sep = "_", remove = F) %>%
    dplyr::mutate(plot = variables,       # rename variables for later join
                  type = paste(type, axis, sep = "_")) %>%
    dplyr::select(-variables, -axis)

# wrangle answers to items on each page
item_values <- study1 %>%
    dplyr::select(-c(topic:itemo)) %>%
    pivot_longer(2:169, names_to = "variables", values_to = "values", 
                 values_transform = as.character) %>%
    dplyr::mutate(variables = case_when(      # recode variable names that have
        variables == "sensi_6" ~ "sensi_06",  # accidentally been labeled
        variables == "acccl_6" ~ "acccl_06",  # without zero
        variables == "accu3_6" ~ "accu3_06",
        variables == "accov_6" ~ "accov_06",
        variables == "diffi_6" ~ "diffi_06",
        variables == "infor_6" ~ "infor_06",
        variables == "value_6" ~ "value_06",
        TRUE ~ variables 
    )) %>%
    dplyr::mutate(plot = paste0("plotx_", str_sub(variables, -2, -1)), # create variable for later join
                  variables = str_sub(variables, 1, -4)) %>%    # rename variable names to get a data set 
                                                                # with one line per participant per page
    pivot_wider(id_cols = c(session, plot), names_from = "variables", 
                values_from = "values")


# join the two data sets
study1_w <- full_join(plot_info, item_values, 
                               by = c("session", "plot")) %>% # by participant and page (plot)
    dplyr::select(-values) %>%
    dplyr::mutate(acccl = as.numeric(acccl), # some var need to be defined as
                  accu3 = as.numeric(accu3), # numeric again
                  accov = as.numeric(accov),
                  diffi = as.numeric(diffi),
                  infor = as.numeric(infor),
                  value = as.numeric(value),
                  effsize = as.numeric(effsize),
                  effsize_cl = case_when( # there is no negative Cliff's Delta, so we have to compute two transformations
                      effsize > 0 ~   (((2*pnorm(effsize/2))-1)/pnorm(effsize/2)), # transform the actual effect size Cohen's d to Cliff's Delta
                      effsize < 0 ~ (- (((2*pnorm(abs(effsize)/2))-1)/pnorm(abs(effsize)/2))) # transform the actual effect size Cohen's d to Cliff's Delta and make it negative as in the item
                  ),
                  effsize_u3 = pnorm(effsize), # transform the actual effect size Cohen's d to Cohen's U3
                  effsize_ov = 2 * pnorm(-abs(effsize) / 2), # transform the actual effect size Cohen's d to overlap
                  acccl_eff = (acccl - effsize_cl)/2, # actual accuracy of rating relative to depicted effectsize on plot
                  accu3_eff = (accu3/100) - effsize_u3, # actual accuracy of rating relative to depicted effectsize on plot
                  accov_eff = (accov/100) - effsize_ov, # actual accuracy of rating relative to depicted effectsize on plot
                  diffi_normed = ((diffi - 1)  / 3) - 1, # transform item to -1 to 1
                  infor_normed = ((infor - 1)  / 3) - 1, # transform item to -1 to 1
                  value_normed = ((value - 1)  / 3) - 1) # transform item to -1 to 1



######### TIMESTAMP DATA ######################################################
# import data
study1_timestamp <- rio::import("data/teachers_study1_N40_detailed.csv")


# wrangle data
study1_timestamp <- study1_timestamp %>%
    mutate(plot = paste0("plotx_", str_sub(item_name, -2, -1))) %>%  # create var with plot number
    dplyr::filter(str_detect(item_name, "sensi|acccl|accu3|accov")) %>% # we only need vars sensitivity or accuracy
    mutate(item_name = str_sub(item_name, 1, 5)) %>%  # delete the page number in item name
    dplyr::select(session, item_name, answer, answered_relative, plot) %>% 
    pivot_wider(id_cols = c(session, plot), names_from = item_name, # make structure similar to existing data set
                values_from = answered_relative) %>%
    mutate(plot = ifelse(plot == "plotx__6", "plotx_06", plot))%>% # recode wrong item labelling
    rowwise() %>%
    mutate(effic = min(sensi, acccl, accu3, accov, na.rm=T)) %>% # what was the the time of the first item to be clicked?
    dplyr::select(session, plot, effic)


# join data and time stamps
study1_w_timestamp <- left_join(study1_w, study1_timestamp, by=c("session", "plot"))



### generate data set so that the six plots from the same type are ordered
### one after the other (and not 1-24)
study1_w_timestamp <- study1_w_timestamp %>%
    group_by(session, type) %>%
    mutate(plotNrWithin = 1:6) %>%
    ungroup() %>% 
    group_by(plotNrWithin, type) %>% 
    mutate(effic_10righttrunc = ifelse(effic > quantile(effic, .9), NA, effic),
           effic_05righttrunc = ifelse(effic > quantile(effic, .95), NA, effic),
           log_effic_05righttrunc =log(effic_05righttrunc),
           log_effic_10righttrunc = log(effic_10righttrunc),
           plotNrWithin0 = plotNrWithin -1) %>% 
    ungroup()

```


# Limited Regression Decay

## Visualisation
### Raw data
```{r}
library(ggforce)
ggplot(study1_w_timestamp, aes(as.factor(plotNrWithin), effic)) +
    geom_sina() +
    coord_cartesian(ylim = c(0,100000)) + 
    geom_smooth(aes(plotNrWithin, effic)) +
    facet_wrap(~type)
```

### 5% Percent truncated of the top
```{r}
ggplot(study1_w_timestamp, aes(as.factor(plotNrWithin), effic_05righttrunc)) +
    geom_sina() +
   # coord_cartesian(ylim = c(0,100000)) + 
    geom_smooth(aes(plotNrWithin, effic_05righttrunc)) +
    facet_wrap(~type)
```


### 10% Percent truncated of the top
```{r}
ggplot(study1_w_timestamp, aes(as.factor(plotNrWithin), effic_10righttrunc)) +
    geom_sina() +
    #coord_cartesian(ylim = c(0,100000)) + 
    geom_smooth(aes(plotNrWithin, effic_10righttrunc)) +
    facet_wrap(~type)
```

### log'ed
```{r}
ggplot(study1_w_timestamp, aes(as.factor(plotNrWithin), log(effic_05righttrunc))) +
    geom_sina() +
    geom_smooth(aes(plotNrWithin, log(effic_05righttrunc))) +
    facet_wrap(~type)
```


## Modelling with `{brms}`

```{r}

# Generate Dummy Variables
study1_w_timestamp <- study1_w_timestamp %>%
    dplyr::mutate(GardnerX = ifelse(type == "gardneraltman_xaxis", 1, 0),
                  HalfeyeX = ifelse(type == "halfeye_xaxis", 1, 0),
                  HalfeyeY = ifelse(type == "halfeye_yaxis", 1, 0),
                  RaincloY = ifelse(type == "raincloud_yaxis", 1, 0))



fit_limDecReg <- brm(
    bf(# define model
       effic_05righttrunc ~ Asym + # Overall asymptote
       (R0-Asym)*
           # curve parameters for plot type dummies  (reference category: GardnerX)
            exp(k*plotNrWithin0),
       
       # define non-linear parameters
       Asym + R0 + k ~ 1,  
       nl = TRUE), # with nl = T a non-linear model is computed
    data = study1_w_timestamp,
    prior = c(
        prior(normal(0,1000), nlpar = "Asym"),
        prior(normal(0,1000), nlpar = "R0"),
        prior(normal(0,1), nlpar = "k")
        ),
    save_pars = save_pars(all = T)
    )

fit_limDecReg_type <- brm(
    bf(# define model
       effic_05righttrunc ~ Asym + # Overall asymptote
       # asymptotes for plot type dummies (reference category: GardnerX)
       AsymshiftHalfeyeX*HalfeyeX +
       AsymshiftHalfeyeY*HalfeyeY +
       AsymshiftRaincloY*RaincloY +
       (R0-(Asym +
            AsymshiftHalfeyeX*HalfeyeX +
            AsymshiftHalfeyeY*HalfeyeY +
            AsymshiftRaincloY*RaincloY))*
           # curve parameters for plot type dummies  (reference category: GardnerX)
            exp((k +
                 kshiftHalfeyeX*HalfeyeX +
                 kshiftHalfeyeY*HalfeyeY +
                 kshiftRaincloY*RaincloY )*plotNrWithin0),
       
       # define non-linear parameters
       AsymshiftHalfeyeX + AsymshiftHalfeyeY + AsymshiftRaincloY +
           kshiftHalfeyeX + kshiftHalfeyeY + kshiftRaincloY +
           Asym + R0 + k ~ 1,  
       nl = TRUE), # with nl = T a non-linear model is computed
    data = study1_w_timestamp,
    prior = c(
        prior(normal(0,1000), nlpar = "Asym"),
        prior(normal(0,1000), nlpar = "R0"),
        prior(normal(0,1), nlpar = "k"),
        prior(normal(0,1000), nlpar = "AsymshiftHalfeyeX"),
        prior(normal(0,1000), nlpar = "AsymshiftHalfeyeY"),
        prior(normal(0,1000), nlpar = "AsymshiftRaincloY"),
        prior(normal(0,1), nlpar = "kshiftHalfeyeX"),
        prior(normal(0,1), nlpar = "kshiftHalfeyeY"),
        prior(normal(0,1), nlpar = "kshiftRaincloY")
        ),
    save_pars = save_pars(all = T)
    )

bayes_factor(fit_limDecReg_type, fit_limDecReg)
```


## Modelling with linear models on log'ed data
```{r}
library(BayesFactor)
# time = 1
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 1) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)

# time = 2
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 2) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)

# time = 3
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 3) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)

# time = 4
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 4) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)

# time = 5
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 5) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)

# time = 6
lmBF(formula = log_effic_05righttrunc ~ type,
     data = study1_w_timestamp %>%
         filter(plotNrWithin == 6) %>%
         select(type, log_effic_05righttrunc) %>%
         mutate(type = as.factor(type)) %>%
         na.omit()
)
```


## Modelling with linear models on log'ed data + ES as predictor
```{r}
library(BayesFactor)
## time = 1
# model with type and effsize
fit_log_time1_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 1) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time1_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 1) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time1_mod1 / fit_log_time1_mod0



## time = 2
# model with type and effsize
fit_log_time2_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 2) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time2_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 2) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time2_mod1 / fit_log_time2_mod0

## time = 3
# model with type and effsize
fit_log_time3_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 3) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time3_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 3) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time3_mod1 / fit_log_time3_mod0



## time = 4
# model with type and effsize
fit_log_time4_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 4) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time4_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 4) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time4_mod1 / fit_log_time4_mod0



## time = 5
# model with type and effsize
fit_log_time5_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 5) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time5_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 5) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time5_mod1 / fit_log_time5_mod0



## time = 6
# model with type and effsize
fit_log_time6_mod1 <- lmBF(formula = log_effic_05righttrunc ~ type + effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 6) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# model with effsize only
fit_log_time6_mod0 <- lmBF(formula = log_effic_05righttrunc ~ effsize,
                         data = study1_w_timestamp %>%
                             filter(plotNrWithin == 6) %>%
                             select(type, log_effic_05righttrunc, effsize) %>%
                             mutate(type = as.factor(type)) %>%
                             na.omit()
                         )

# BF between the two models
fit_log_time6_mod1 / fit_log_time6_mod0
```

